### ISSUE TITLE
Gulp Starter Kit

### ISSUE THREAD

**Issue by jr-cologne** [gr8arty/gulp-sandbox#1]
Hi @gr8arty,
just wanted to let you know that I haven't forgotten you.
Are you still experiencing the reloading issue with pug templating files or what is your current status in general?
I am hoping to find some time this week in order to continue working on the Gulp starter kit.
Looking forward to hear from you.
Best regards,
@jr-cologne

**Comment by jr-cologne** [comment]
Hi @gr8arty,
I've just released [v0.7.0-alpha](https://github.com/jr-cologne/gulp-starter-kit/releases/tag/v0.7.0-alpha) of my Gulp Starter Kit which now supports pug.
Feel free to test this out. Would be happy to hear from you.
Best regards,
@jr-cologne

**Comment by gr8arty** [comment]
> 
> 
> Hi @gr8arty,
> just wanted to let you know that I haven't forgotten you.
> Are you still experiencing the reloading issue with pug templating files or what is your current status in general?
> I am hoping to find some time this week in order to continue working on the Gulp starter kit.
> Looking forward to hear from you.
> Best regards,
> @jr-cologne

Hi @jr-cologne ! 
Yeah, I just forgot to tell you I have fixed that issue, the problem was laying in the order of watch and reload tasks, I have changed the order and now it works as it should be. Thanks for getting back anyway!  

Sure, I'll definitely check the updated Gulp Starter Kit, and I'll leave feedback if I've noticed any issues. Will keep you in touch and thanks for keeping me updated!

Mm, I would like to ask you, just out of curious, have you got some roadmap of this project for the near future?

**Comment by jr-cologne** [comment]
Hi @gr8arty,
Sounds great. Happy to hear that you already resolved the issue.

As described in my "first stable version" issue, I'm aiming to finish v1 in July/August.
Most of the features which are going to be implemented are actually already in the Gulp Starter Kit which is why I'm going to release a beta version very soon.
After that, there will only be bug fixes and enhancements for the most part.
In case you have any ideas regarding features and enhancements which should definitely be implemented, feel free to let me know.
In the end, I would like to have a Gulp Starter Kit which is configured when installing.
For instance, it would then ask you whether you want to use Pug or what CSS preprocessor you want to use. So, the installation would be based on your specific needs and choices.

Well, thank you in advance for testing out my newest release as well as your general interest in my work at this project.

Best regards,
@jr-cologne

**Comment by gr8arty** [comment]
Awesome! Glad to hear that, there's definitely enough of time to complete it in time. This beta version is already well suited for production use but I have some suggestion for current folders' structure, these are minor changes but nonetheless they have importance in them.
As I see it, for pug directory I would add a few subdirectories which could add to it more flexibility
For instance : 
```
src/pug/                         or   src/pug/
      modules/footer/footer.pug          includes/header.pug, footer.pug
              header/header.pug          layouts/default.pug 
      pages/                             utils/mixins.pug   
      templates/default.pug              index.pug   
      utils/mixins.pug                                                
      index.pug
```
And I think to add a few more things (_optionally_) like:
- gulp-webp 
- some svg manipulation like _gulp-svgmin_
- gulp-html-beautify

And additionally concerning options of whether to use pug or not, you can make separate repo with pug setup so it would be easier for users to choose between the two. 

These are some of my ideas which I can think of now, if there would be more I'll let you know about them. It's my pleasure to take part in this project and to share my thoughts on this one. 
Thank you for doing this.

**Comment by jr-cologne** [comment]
Thank you so much for your suggestions, @gr8arty. This is really helpful!

Here're my considerations:

- The second folder structure for pug looks fine to me. Great idea! 👍
- Converting images to webp would be cool as an optional feature (later, not in beta)
- SVG images should already be compressed thanks to `gulp-imagemin`
- Why would I beautify my HTML in production? I would rather minify it in production or use something like Prettier during development.

I'm happy to get some fresh ideas/inspiration, so I'm going to add the first two points to my agenda in the issue jr-cologne/gulp-starter-kit#11.

**Comment by gr8arty** [comment]
Hi @jr-cologne 
Good to hear you liked that! 
Actually, that's true. I've just checked, you're right gulp-imagemin minifies SVG as well and that will do. 
Yes, I had a bit of doubt about gulp-html-beautify at first, but if you do normal development mode without pug that could be helpful. But I understand there're other options of how it can be implemented like "prettier" or gulp-pretty-html. It's not really necessary, maybe it's even superfluous... just shared my suggestion. Anyway, I think it's better to offer all the ideas and pick a few out of many! 
Okay, if anything new will come up I'll let you know.

**Comment by jr-cologne** [comment]
Great, thank you for your clarifications.

Well, like you said: better offer all the ideas no matter whether they might end up being accepted and implemented or not. So, don't hesitate to come up with any crazy ideas. :laughing:

I actually don't think that beautifying HTML is unnecessary or something like that, especially if the source code is also touched by many other developers. It's just that there are probably better tools which are more commonly used for such tasks.
Let's see, might actually turn out that I will implement a similar feature.
